/** @type {import('next-sitemap').IConfig} */
module.exports = {
    siteUrl: process.env.SITE_URL || "https://www.kaisoresearch.com",
    generateRobotsTxt: true,
    sitemapSize: 7000,
    exclude: ["/admin", "/admin/*", "/auth", "/auth/*", "/error", "/report-store/*", "/blog/*", "/admin/dashboard", "/admin/masters/hero-section-form", "/admin/setting", "/auth/back_to_login", "/auth/forgotpassword", "/auth/login", "/auth/setnewpassword", "/auth/verify_code", "/blogDetails", "/checkout", "/cookiepolicy", "/custom-report-form", "/deliveryformats", "/gdrp", "/inquiry-before-buy", "/privacypolicy", "/report-details", "/retunpolicy", "/sitemap", "/success", "/termsandcondition", "/disclaimer"], // exclude private and dynamic routes and pages without generateMetadata
    changefreq: "weekly",
    priority: 0.7,

    // Static route generation
    transform: async (config, path) => {
        return {
            loc: path, // path => /, /about, etc
            changefreq: config.changefreq,
            priority: config.priority,
            lastmod: new Date().toISOString(),
        };
    },

    // Dynamic additional sitemaps - these will be generated by generate-sitemaps.js
    additionalSitemaps: [],
};
