export const API = {
    LOGIN: {
        EMAIL: "email",
        PASSWORD: "password",
    },
    FORGOTPASSWORD: {
        EMAIL: "email",
    },
    VERIFYCODE: {
        OTP: "otp",
    },
    CODEVERIFICATION: {
        FIRSTNAME: "firstName",
        LASTNAME: "lastName",
        MOBILENO: "mobileNumber",
    },
    VERIFYACCOUNT: {
        CODE: "code",
    },
    USERPROFILE: {
        PROFILE_IMAGE: "profileImage",
        FIRSTNAME: "firstName",
        LASTNAME: "lastName",
        PHONENO: "mobileNumber",
        EMAIL: "email",
        WHATSAPPNO: "whatsappNumber",
    },
    ADMIN: {
        FIRSTNAME: "firstName",
        LASTNAME: "lastName",
        PHONENO: "mobileNumber",
        EMAIL: "email",
        WHATSAPPNO: "whatsappNumber",
        ACCESS_ARRAY: "accessArray",
    },
    SERVICES_CREATE_UPDATE: {
        NAME: "name",
        AMOUNT: "amount",
        GST: "gst",
        PRODUCTCODE: "productCode",
        CODE: "productCodeNumber",
        PRODUCTDESC: "description",
    },
    PAYEECREATEUPDATE: {
        FIRST_NAME: "firstName",
        LAST_NAME: "lastName",
        WHATAPPNO: "whatsappNumber",
        CONTACTNO: "mobileNumber",
        EMAIL: "email",
        MAIN: "main",
        SUB: "sub",
    },
    PAYEECREATEUPDATEMAIN: {
        COMPANYID: "companyId",
        PERSONALEMAIL: "email",
        COMPANY_NAME: "name",
        GSTNO: "gstNumber",
        CAAPARMENT: "number",
        WHATSAPP_NUMBER: "whatsappNumber",
        CABUILDING: "addressOne",
        CASTREET: "addressTwo",
        CALANDMARK: "landMark",
        CITY: "city",
        STATE: "state",
        ZIPCODE: "postalCode",
        COUNTRY: "country",
        COUNTRYID: "countryId",
        STATEID: "stateId",
    },
    PAYEECREATEUPDATESUB: {
        SUBCOMPANYID: "subCompanyId",
        PERSONALEMAIL: "email",
        COMPANY_NAME: "name",
        GSTNO: "gstNumber",
        WHATSAPP_NUMBER: "whatsappNumber",
        CAAPARMENT: "number",
        CABUILDING: "addressOne",
        CASTREET: "addressTwo",
        CALANDMARK: "landMark",
        CITY: "city",
        STATE: "state",
        ZIPCODE: "postalCode",
        COUNTRY: "country",
        COUNTRYID: "countryId",
        STATEID: "stateId",
    },
    SETTING: {
        ADDRESSID: "addressId",
        COMPANYID: "companyId",
        PROFILE_IMAGE: "companyLogo",
        COMPANY_NAME: "companyName",
        CONTACTNO: "whatsappNumber",
        GSTNO: "gstNumber",
        WEBSIE: "website",
        EMAILADDRESS: "email",
        CAAPARMENT: "number",
        CABUILDING: "addressOne",
        CASTREET: "addressTwo",
        CALANDMARK: "landMark",
        CITY: "city",
        STATE: "state",
        ZIPCODE: "postalCode",
        COUNTRY: "country",
        BANKDETAIL: "bank",
        COUNTRYID: "countryId",
        STATEID: "stateId",
    },
    SETTIGBANK: {
        BANKID: "bankId",
        BANKNAME: "name",
        ACCOUNTHOLDERNAME: "accountHolderName",
        ACCOUNTNO: "accountNumber",
        IFSC: "IFSCCode",
    },
    INVOICECREATEUPDATE: {
        PAYEEID: "payeeId",
        COMPANYID: "companyId",
        BANKID: "bankId",
        DATE: "date",
        DUEDATE: "dueDate",
        ISTAXABLE: "isTaxable",
        CGST: "CGST",
        SGST: "SGST",
        IGST: "IGST",
        UTGST: "UTGST",
        SUBTOTAL: "subTotal",
        DISCOUNT: "discount",
        ROUNDOFF: "roundOff",
        TOTALAMOUNT: "totalAmount",
        NOTES: "notes",
        SERVICESARRAY: "serviceArray",
    },
    INVOICESERVICESARRAY: {
        SERVICESID: "serviceInvoiceId",
        SERVICESCREATEID: "serviceId",
        NAME: "name",
        RATE: "rate",
        QUONTITY: "quantity",
        CGST: "CGST",
        SGST: "SGST",
        IGST: "IGST",
        UTGST: "UTGST",
        DISCOUNT: "discount",
        PRODUCTCODE: "productCodeNumber",
        TOTALAMOUNT: "totalAmount",
    },
    PAYMENTCREATEUPDATE: {
        INVOICEIS: "invoiceId",
        PAYEEID: "payeeId",
        RECEIVEDBY: "receivedBy",
        PAYMENTDATE: "paymentDate",
        INVOICETOTAL: "invoiceTotal",
        RECIVEDAMOUNT: "receivedAmount",
        TDS: "TDS",
        ROUNDOFF: "roundOff",
        OUTSTANDING: "outstanding",
        METHOD: "method",
        NOTES: "notes",
    },
    CONTACTUS: {
        NAME: "name",
        EMAIL: "email",
        MESSAGE: "message",
    },
    PAYMENTDETAIL: {
        SUBID: "subscription_id",
        EMAIL: "email",
        CURRENCY: "currency",
        CONTACT: "contact",
    },
    REPORT_CREATE_EDIT: {
        SINGLE_USER_PRICE: "singleUserPrice",
        BUSINESS_PRICE: "businessPrice",
        ENTREPRENEUR_PRICE: "entrepreneurPrice",
        PAGES: "pages",
        PUBLISH_DATE: "publishDate",
        CATEGORY_ID: "categoryId",
        SUBCATEGORY_ID: "subCategoryId",
        REPORT_TITLE: "reportTitle",
        REPORT_SUBTITLE: "reportSubTitle",
        REPORT_OVERVIEW: "reportOverview",
        TABLE_OF_CONTENT: "tableOfContent",
        AVAILABLE_IN: "availableIn",
        INTERNET_HANDLING_CHARGE: "internetHandlingCharge",
        SEO_TITLE: "seoTitle",
        META_DESCRIPTION: "metaDescription",
        KEYWORDS: "keywords",
        URL: "url",
        STATUS: "status",
        AUTHOR: "author",
        REPORT_DESCRIPTION: "reportDescription",
    },
    ARTICLE_CREATE_EDIT: {
        ARTICLE_TITLE: "blogTitle",
        ARTICLE_SUBTITLE: "blogSubTitle",
        ARTICLE_TYPE: "type",
        CATEGORY_ID: "categoryId",
        SUBCATEGORY_ID: "subCategoryId",
        ARTICLE_CONTENT: "description",
        SEO_TITLE: "seoTitle",
        META_DESCRIPTION: "metaDescription",
        KEYWORDS: "keywords",
        URL: "url",
        PUBLISH_DATE: "publishDate",
        BLOG_IMAGE: "image",
        STATUS: "status",
    },
    REPORTING_SETTING: {
        REPORT_BUTTON_ID: "reportButtonId",
        REQUEST_BUTTON: "requestButton",
        BUY_BUTTON: "buyButton",
        INQUIRE_BUTTON: "inquiryButton",
        RESEARCH_METHODOLOGY: "researchMethodology",
    },
};
